<?xml version="1.0"?>
<robot name="fotokite" xmlns:xacro="http://www.ros.org/wiki/xacro">



    <xacro:macro name="fotokite_arm" params="parent *origin">

        <xacro:property name="PI" value="3.14159265359"/>

        <!-- Joints Control in Gazebo -->
        <!--gazebo>
            <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
        </gazebo-->

        <!-- Geometrical properties -->
        <xacro:property name="link_side"    value="0.02"/>
        <xacro:property name="joint_radius" value="0.018"/>
        <xacro:property name="joint_length" value="0.025"/>
        <xacro:property name="length"       value="0.04"/>

        <!-- Materials -->
        <material name="orange">
            <color rgba="1.00 0.67 0.02 1.00"/>
        </material>

        <material name="gray">
            <color rgba="0.80 0.80 0.80 1.00"/>
        </material>

        <!-- Generates a box visual/collision/inertial -->
        <xacro:macro name="prism_vci" params="side length mass:=1 *origin">
            <xacro:macro name="prism_geometry">
                <xacro:insert_block name="origin"/>
                <geometry>
                    <box size="${side} ${side} ${length}"/>
                </geometry>
            </xacro:macro>
            <visual>
                <xacro:prism_geometry/>
                <material name="orange"/>
            </visual>
            <collision>
                <xacro:prism_geometry/>
            </collision>

            <inertial>
                <xacro:insert_block name="origin"/>
                <mass value="${mass}"/>
                <inertia ixx="${(mass/12)*(side*side+length*length)}"
                         iyy="${(mass/12)*(side*side+length*length)}"
                         izz="${(mass/6)*(side*side)}"
                         ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </xacro:macro>

        <!-- Generates a cylinder visual/collision -->
        <xacro:macro name="cylinder_vc" params="radius length *origin">
            <xacro:macro name="cylinder_geometry">
                <xacro:insert_block name="origin"/>
                <geometry>
                    <cylinder length="${length}" radius="${radius}"/>
                </geometry>
            </xacro:macro>
            <visual>
                <xacro:cylinder_geometry/>
                <material name="gray"/>
            </visual>
            <collision>
                <xacro:cylinder_geometry/>
            </collision>
        </xacro:macro>

        <!-- Generates child joint of parent -->
        <xacro:macro name="arm_joint" params="prefix parent child axis dist:=0 joint_type lower upper index">

        <!--xacro:unless value="${child == 'arm'}"-->
            <joint name="${prefix}_${parent}_${child}_joint" type="${joint_type}">
                <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
                <parent link="${prefix}_${parent}"/>

                <xacro:if value="${index == 0}">
                    <child link="${prefix}_${child}"/>
                </xacro:if>

                <!--xacro:if value="${parent == 'length'}"-->
                    <xacro:if value="${index == 1}">
                        <child link="module_2_${child}"/>
                    </xacro:if>
                    <xacro:if value="${index == 2}">
                        <child link="module_3_${child}"/>
                    </xacro:if>
                    <xacro:if value="${index == 3}">
                        <child link="wrist_${child}"/>
                    </xacro:if>
                <!--/xacro:if-->

                <axis xyz="${axis}"/>

                <limit effort="40.0"
                       velocity="1.0"
                       lower="${lower}"
                       upper="${upper}"/>
            </joint>

            <!-- Transmission -->
            <!--transmission name="${parent}_${child}_transmission">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="${prefix}_${parent}_${child}_joint">
                    <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                </joint>
                <actuator name="${prefix}_${parent}_${child}_actuator">
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
            </transmission-->

            <!-- Links -->
            <link name="${prefix}_${parent}">

                <xacro:prism_vci length="${dist}" side="${link_side}">
                    <origin xyz="0 0 ${dist/2}" rpy="0 0 0"/>
                </xacro:prism_vci>

                <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">

                    <xacro:if value="${axis=='0 0 1'}">
                        <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
                    </xacro:if>
                    <xacro:if value="${axis=='1 0 0'}">
                        <origin xyz="0 0 ${dist}" rpy="0 ${PI/2} 0"/>
                    </xacro:if>
                    <xacro:if value="${axis=='0 1 0'}">
                        <origin xyz="0 0 ${dist}" rpy="${PI/2} 0 0"/>
                    </xacro:if>

                </xacro:cylinder_vc>

            </link>

            <gazebo reference="${prefix}_${parent}">
                <xacro:if value="${prefix == 'module_1'}">
                    <material>Gazebo/Orange</material>
                </xacro:if>
                <xacro:if value="${prefix == 'module_2'}">
                    <material>Gazebo/Blue</material>
                </xacro:if>
                <xacro:if value="${prefix == 'module_3'}">
                    <material>Gazebo/Yellow</material>
                </xacro:if>
                <xacro:if value="${prefix == 'wrist'}">
                    <material>Gazebo/Green</material>
                </xacro:if>

            </gazebo>

        </xacro:macro>

        <!-- Uncomment for RViz with fake joints -->
        <!-- Uncomment for Gazebo -->
        <!--link name="${parent}"/-->

        <!-- Uncomment for RViz with fake joints -->
        <!-- Uncomment for Gazebo -->
        <!-- Arm fixed to world frame  -->


        <!-- Joints Chain -->
        <xacro:arm_joint   prefix="module_1"    parent="yaw"      child="pitch"     axis="0 0 1" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_1"    parent="pitch"    child="roll"      axis="0 1 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_1"    parent="roll"     child="length"    axis="1 0 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_1"    parent="length"   child="yaw"       axis="0 0 1" dist="${length}"  joint_type="prismatic"  lower="0"           upper="2"       index="1"/>
        <xacro:arm_joint   prefix="module_2"    parent="yaw"      child="pitch"     axis="0 0 1" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_2"    parent="pitch"    child="roll"      axis="0 1 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_2"    parent="roll"     child="length"    axis="1 0 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_2"    parent="length"   child="yaw"       axis="0 0 1" dist="${length}"  joint_type="prismatic"  lower="0"           upper="2"       index="2"/>
        <xacro:arm_joint   prefix="module_3"    parent="yaw"      child="pitch"     axis="0 0 1" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_3"    parent="pitch"    child="roll"      axis="0 1 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_3"    parent="roll"     child="length"    axis="1 0 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="module_3"    parent="length"   child="pitch"     axis="0 0 1" dist="${length}"  joint_type="prismatic"  lower="0"           upper="2"       index="3"/>
        <xacro:arm_joint   prefix="wrist"       parent="pitch"    child="yaw"       axis="0 1 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="wrist"       parent="yaw"      child="roll"      axis="0 0 1" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>
        <xacro:arm_joint   prefix="wrist"       parent="roll"     child="finger"    axis="1 0 0" dist="${length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   index="0"/>

        <link name="wrist_finger">
          <inertial>
            <mass value="1.477" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01152" ixy="0.0" ixz="0.0" iyy="0.01152" iyz="0.0" izz="0.0218" />
          </inertial>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <mesh filename="package://arm_description/meshes/ardrone.dae"/>
            </geometry>
          </visual>

          <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <!--mesh filename="package://arm_description/urdf/ardrone.dae"/-->
              <box size="0.001 0.001 0.001"/>
            </geometry>
          </collision>
        </link>

        <joint name="${parent}_module_1_joint" type="fixed">
            <xacro:insert_block name="origin" />
            <parent link="${parent}"/>
            <child link="module_1_yaw"/>
        </joint>

        <!--gazebo reference="arm">
        <material>Gazebo/Red</material>
        </gazebo-->
    </xacro:macro>

</robot>
