<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.14159265359"/>

  <!-- Joints Control in Gazebo -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
  </gazebo>

  <!-- Geometrical properties -->
  <xacro:property name="link_side"      value="0.02"/>
  <xacro:property name="joint_radius"   value="0.018"/>
  <xacro:property name="joint_length"   value="0.025"/>
  <xacro:property name="toe_length"     value="0.03"/>
  <xacro:property name="foot_length"    value="0.04"/>
  <xacro:property name="knee_length"    value="0.04"/>
  <xacro:property name="lap_length"     value="0.04"/>
  <xacro:property name="hip_length"     value="0.04"/>
  <xacro:property name="arm_length"     value="0.04"/>
  <xacro:property name="hand_length"    value="0.04"/>
  <xacro:property name="finger_length"  value="0.04"/>

  <!-- Materials -->
  <material name="orange">
    <color rgba="1.00 0.67 0.02 1.00"/>
  </material>

  <material name="gray">
    <color rgba="0.80 0.80 0.80 1.00"/>
  </material>

  <!-- Generates a box visual/collision/inertial -->
  <xacro:macro name="prism_vci" params="side length mass:=1 *origin">

    <xacro:macro name="prism_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <box size="${side} ${side} ${length}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:prism_geometry/>
      <material name="orange"/>
    </visual>

    <collision>
      <xacro:prism_geometry/>
    </collision>

    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${(mass/12)*(side*side+length*length)}"
               iyy="${(mass/12)*(side*side+length*length)}"
               izz="${(mass/6)*(side*side)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>

  </xacro:macro>

  <!-- Generates a cylinder visual/collision -->
  <xacro:macro name="cylinder_vc" params="radius length *origin">

    <xacro:macro name="cylinder_geometry">
      <xacro:insert_block name="origin"/>
      <geometry>
        <cylinder length="${length}" radius="${radius}"/>
      </geometry>
    </xacro:macro>

    <visual>
      <xacro:cylinder_geometry/>
      <material name="gray"/>
    </visual>

    <collision>
      <xacro:cylinder_geometry/>
    </collision>

  </xacro:macro>

  <!-- Generates child joint of parent -->
  <xacro:macro name="arm_joint" params="child parent dist:=0 axis joint_type lower upper">

    <!--xacro:unless value="${child == 'arm'}"-->
        <joint name="${parent}_${child}_joint" type="${joint_type}">
            <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
            <parent link="${parent}"/>
            <child link="${child}"/>
            <axis xyz="${axis}"/>

            <!--xacro:unless value="${joint_type == 'prismatic'}"-->
                <limit effort="40.0"
                       velocity="1.0"
                       lower="${lower}"
                       upper="${upper}"/>
            <!--/xacro:unless-->

            <!--xacro:if value="${joint_type == 'prismatic'}">
                <limit effort="40.0"
                       velocity="1.0"
                       lower="${0}"
                       upper="${2}"/>
            </xacro:if-->


        </joint>
    <!--/xacro:unless-->

    <!--xacro:if value="${child == 'arm'}">
        <joint name="${parent}_${child}_joint" type="prismatic">
          <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
          <parent link="${parent}"/>
          <child link="${child}"/>
          <axis xyz="${axis}"/>
          <limit effort="40.0"
                 velocity="1.0"
                 lower="${0.0}"
                 upper="${0.5}"/>
        </joint>
    </xacro:if-->

    <!-- Required for ROS control -->
    <transmission name="${parent}_${child}_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${parent}_${child}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${parent}_${child}_actuator"/>
    </transmission>

    <link name="${parent}">

      <xacro:prism_vci length="${dist}" side="${link_side}">
        <origin xyz="0 0 ${dist/2}" rpy="0 0 0"/>
      </xacro:prism_vci>

      <xacro:cylinder_vc radius="${joint_radius}" length="${joint_length}">

        <xacro:if value="${axis=='0 0 1'}">
          <origin xyz="0 0 ${dist}" rpy="0 0 0"/>
        </xacro:if>

        <xacro:if value="${axis=='1 0 0'}">
          <origin xyz="0 0 ${dist}" rpy="0 ${PI/2} 0"/>
        </xacro:if>

        <xacro:if value="${axis=='0 1 0'}">
          <origin xyz="0 0 ${dist}" rpy="${PI/2} 0 0"/>
        </xacro:if>

      </xacro:cylinder_vc>

    </link>

    <gazebo reference="${parent}">
      <material>Gazebo/Orange</material>
    </gazebo>

  </xacro:macro>

  <!-- Uncomment for RViz with fake joints -->
  <!-- World frame (for Gazebo) -->
  <!--link name="world"/-->

  <!-- Uncomment for RViz with fake joints -->
  <!-- Arm fixed to world frame  -->
  <!--joint name="world_foot_joint" type="fixed">
    <parent link="world"/>
    <child link="toe"/>
  </joint-->

  <!-- Joints Chain -->
  <xacro:arm_joint parent="toe"     child="foot"    axis="0 0 1" dist="${toe_length}"   joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="foot"    child="knee"    axis="1 0 0" dist="${foot_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="knee"    child="lap"     axis="0 1 0" dist="${knee_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="lap"     child="hip"     axis="0 0 1" dist="${lap_length}"   joint_type="prismatic"  lower="0"           upper="2"       />
  <xacro:arm_joint parent="hip"     child="arm"     axis="0 0 1" dist="${hip_length}"   joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="arm"     child="hand"    axis="0 1 0" dist="${arm_length}"   joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="hand"    child="toe_2"  axis="1 0 0" dist="${hand_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <!--xacro:arm_joint parent="base_2"  child="toe_2"   axis="1 0 0" dist="${hand_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   /-->
  <xacro:arm_joint parent="toe_2"   child="foot_2"  axis="0 0 1" dist="${toe_length}"   joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="foot_2"  child="knee_2"  axis="1 0 0" dist="${foot_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="knee_2"  child="lap_2"   axis="0 1 0" dist="${knee_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="lap_2"   child="hip_2"   axis="0 0 1" dist="${lap_length}"   joint_type="prismatic"  lower="0"           upper="2"       />
  <xacro:arm_joint parent="hip_2"   child="arm_2"   axis="0 0 1" dist="${hip_length}"   joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="arm_2"   child="hand_2"  axis="0 1 0" dist="${arm_length}"   joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />
  <xacro:arm_joint parent="hand_2"  child="finger"  axis="1 0 0" dist="${hand_length}"  joint_type="revolute"   lower="${-PI}"      upper="${PI}"   />

  <!-- End effector -->
  <!--link name="finger">
    <xacro:prism_vci length="${finger_length}" side="${link_side}">
      <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
    </xacro:prism_vci>
  </link-->
  <link name="finger">
      <inertial>
        <mass value="1.477" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.01152" ixy="0.0" ixz="0.0" iyy="0.01152" iyz="0.0" izz="0.0218" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://arm_description/meshes/ardrone.dae"/>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <!--mesh filename="package://arm_description/urdf/ardrone.dae"/-->
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
  </link>

  <!--gazebo reference="arm">
    <material>Gazebo/Red</material>
  </gazebo-->

</robot>
