fotokite_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - toe_foot_joint
        - foot_knee_joint
        - knee_lap_joint
        - lap_hip_joint
        - hip_arm_joint
        - arm_hand_joint
        - hand_finger_joint
    gains:
        toe_foot_joint:     {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}
        foot_knee_joint:    {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}
        knee_lap_joint:     {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}
        lap_hip_joint:      {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}
        hip_arm_joint:      {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}
        arm_hand_joint:     {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}
        hand_finger_joint:  {p: 6.0, d: 4.0, i: 0.0, i_clamp: 0.0}

    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        toe_foot_joint: {trajectory: 0.1, goal: 0.1}
        foot_knee_joint: {trajectory: 0.1, goal: 0.1}
        knee_lap_joint: {trajectory: 0.1, goal: 0.1}
        lap_hip_joint: {trajectory: 0.1, goal: 0.1}
        hip_arm_joint: {trajectory: 0.1, goal: 0.1}
        arm_hand_joint: {trajectory: 0.1, goal: 0.1}
        hand_finger_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
