controller_list:
  - name: fake_arm_1_controller
    joints:
      - toe_foot_joint
      - foot_knee_joint
      - knee_lap_joint
      - lap_hip_joint
      - hip_arm_joint
      - arm_hand_joint
      - hand_toe_2_joint
  - name: fake_arm_2_controller
    joints:
      - hand_toe_2_joint
      - toe_2_foot_2_joint
      - foot_2_knee_2_joint
      - knee_2_lap_2_joint
      - lap_2_hip_2_joint
      - hip_2_arm_2_joint
      - arm_2_hand_2_joint
      - hand_2_finger_joint