controller_list:
  - name: fake_arm_controller
    joints:
      - toe_foot_joint
      - foot_knee_joint
      - knee_lap_joint
      - lap_hip_joint
      - hip_arm_joint
      - arm_hand_joint
      - hand_finger_joint