fotokite_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  wrist_group_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - wrist_pitch_yaw_joint
      - wrist_yaw_roll_joint
      - wrist_roll_finger_joint

  fotokite_group_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - wrist_pitch_yaw_joint
      - wrist_yaw_roll_joint
      - wrist_roll_finger_joint
