controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - toe_foot_joint
    - foot_leg_joint
    - leg_arm_joint
    - arm_hand_joint
    - hand_finger_joint